
(define (day-of-week x)
	(case x
		((1) "Monday")
		((2) "Tuesday")
		((3) "Wednesday")
		((4) "Thursday")
		((5) "Friday")
		((6) "Saturday")
		((7) "Sunday")
		(else "Invalid day of week")))

(define (day-of-week-num day) 
	(case day
		(("Monday") 1)
		(("Tuesday") 2)
		(("Wednesday") 3)
		(("Thursday") 4)
		(("Friday") 5)
		(("Saturday") 6)
		(("Sunday") 7)
		(else -1)))

(define (month-of-year x) 
  (case x 
    ((1) "January")
    ((2) "February")
    ((3) "March")
    ((4) "April")
    ((5) "May")
    ((6) "June")
    ((7) "July")
    ((8) "August")
    ((9) "September")
    ((10) "October")
    ((11) "November")
    ((12) "Decemeber")
    (else "Invalid month")))

(define (month-of-year-num x)
  (case x
    (("January") 1)
    (("February") 2)
    (("March") 3)
    (("April") 4)
    (("May") 5)
    (("June") 6)
    (("July") 7)
    (("August") 8)
    (("September") 9)
    (("October") 10)
    (("November") 11)
    (("December") 12)
    (else -1)))


